apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-sidecar
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0
      log_level: "debug"
    positions:
      filename: /tmp/positions.yaml
    clients: # Specify target
      - url: http://loki_url:3100/loki/api/v1/push
    scrape_config:
      - job_name: "nginx"
        static_configs:
          - targets:
              - localhost
            labels:
              app: "storage-service"
              __path__: /var/log/nginx/*.log # Any file .log in the EmptyDir Volume.