apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  serviceName: keycloak
  replicas: 2
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: 'keycloak/keycloak:latest'
        env:
        - name: CACHE_OWNERS_COUNT
          value: '1'
        - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
          value: '1'
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
        - name: KC_PROXY
          value: edge
        - name: PROXY_ADDRESS_FORWARDING
          value: 'true'
        - name: KC_HEALTH_ENABLED
          value: 'true'
        - name: KC_METRICS_ENABLED
          value: 'true'
        - name: KC_HTTP_ENABLED
          value: 'true'
        - name: KC_HTTP_RELATIVE_PATH
          value: /auth
        - name: KC_HOSTNAME_URL
          value: 'https://keycloak.com/auth/'
        - name: KC_HOSTNAME_ADMIN_URL
          value: 'https://keycloak.com/auth/'
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL
          value: 'jdbc:postgresql://localhost:5432/keycloak'
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-info
              key: keycloak_username
        - name: KC_DB_PASSWORD
          secretKeyRef:
              name: db-info
              key: keycloak_password
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: jgroups
            containerPort: 7600
            protocol: TCP
        imagePullPolicy: Always
        args:
          - start
          - '--cache=ispn'
          - '--cache-stack=kubernetes'
          - '--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true'
          - '-Djgroups.dns.query=keycloak.default.svc.cluster.local'
          - --log="console,file" --log-file=/app_log/keycloak.log